### ISSUE TITLE
Add spacing between fa-icon and text

### ISSUE THREAD

**Issue by aashutoshrathi** [hapramp/hapramp-landing#1]
In lines below 
https://github.com/hapramp/hapramp-landing/blob/b22d8771221a3c92076756fc56c7b46ccfb41159/index.html#L572

https://github.com/hapramp/hapramp-landing/blob/b22d8771221a3c92076756fc56c7b46ccfb41159/index.html#L582

before the word begins either add `&nbsp;` or add charachter by pressing `Alt + 255`.

**Before:**
![image](https://user-images.githubusercontent.com/21199234/41802102-316ff59e-769c-11e8-83e9-cab79aebc152.png)

**After:**
![image](https://user-images.githubusercontent.com/21199234/41802086-17158e84-769c-11e8-9fe1-95341c54cd70.png)

**Comment by singhpratyush** [comment]
Fixed in 117af30a1e00c9eaca19d06e02223f0b55fe2af5.
